#
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-zts-node-browsers-legacy
    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: composer install -vvv --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: php vendor/bin/phpunit --verbose
      - run: php php_syntax_checker.php
      - run: php deploy.php
